--TABELA INTERRUPCOES
CREATE TABLE INTERRUPCOES_ANEEL_2023(
"DATA_DADOS" NVARCHAR2(100)
,"CODIGO_UC" NVARCHAR2(100)
,"DSC_ALIMENTADOR_SUBESTACAO" NVARCHAR2(1000)
,"DSC_SUBESTACAO_DISTRIBUICAO" NVARCHAR2(1000)
,"ORDEM_INTERRUPCAO" NVARCHAR2(1000)
,"DSC_TIPO_INTERRUPCAO" NVARCHAR2(100)
,"MOTIVO_EXPURGO" NVARCHAR2(100)
,"DATA_INICIO_INTERRUPCAO" NVARCHAR2(100)
,"DATA_FIM_INTERRUPCAO" NVARCHAR2(100)
,"FATO_GERADOR_INTERRUPCAO" NVARCHAR2(1000)
,"NUM_NIVEL_TENSAO" NUMBER(38,8)
,"NUM_UNIDADE_CONSUMIDORA" NUMBER(38,8)
,"NUM_CONSUMIDOR_CONJUNTO" NUMBER(38,8)
,"ANO" NVARCHAR2(100)
,"AGENTE_REGULADO" NVARCHAR2(1000)
,"SIGLA_AGENTE" NVARCHAR2(100)
,"CPF_CNPJ" NVARCHAR2(100)

);


--CONSULTA COM OS FILTROS
SELECT 
SIGLA_AGENTE
,ANO
,CODIGO_UC
,DSC_ALIMENTADOR_SUBESTACAO
,DSC_SUBESTACAO_DISTRIBUICAO
,ORDEM_INTERRUPCAO
,DSC_TIPO_INTERRUPCAO
,MOTIVO_EXPURGO
,TO_TIMESTAMP(DATA_INICIO_INTERRUPCAO, 'YYYY-MM-DD HH24:MI:SS') AS DATA_INICIO
,TO_TIMESTAMP(DATA_FIM_INTERRUPCAO, 'YYYY-MM-DD HH24:MI:SS') AS DATA_FIM
,TO_DATE(DATA_FIM_INTERRUPCAO, 'YYYY-MM-DD HH24:MI:SS') - TO_DATE(DATA_INICIO_INTERRUPCAO, 'YYYY-MM-DD HH24:MI:SS') AS DATA_DIF
,FATO_GERADOR_INTERRUPCAO
,NUM_NIVEL_TENSAO
,NUM_UNIDADE_CONSUMIDORA
,NUM_CONSUMIDOR_CONJUNTO
FROM INTERRUPCOES_ANEEL_2023
WHERE TO_DATE(DATA_FIM_INTERRUPCAO, 'YYYY-MM-DD HH24:MI:SS') - TO_DATE(DATA_INICIO_INTERRUPCAO, 'YYYY-MM-DD HH24:MI:SS') >= 0.0020833333333
AND MOTIVO_EXPURGO = '0'
AND (SIGLA_AGENTE = 'CPFL-PAULISTA' OR SIGLA_AGENTE = 'CPFL- PIRATININGA' OR SIGLA_AGENTE = 'CPFL Jaguari' OR SIGLA_AGENTE = 'RGE SUL')
AND NUM_UNIDADE_CONSUMIDORA > 0
ORDER BY TO_DATE(DATA_FIM_INTERRUPCAO, 'YYYY-MM-DD HH24:MI:SS') - TO_DATE(DATA_INICIO_INTERRUPCAO, 'YYYY-MM-DD HH24:MI:SS') ASC;




SELECT SIGLA_AGENTE
,(SUM(DATA_DIF)*24) AS HORAS
,COUNT(1) AS TOTAL_INTERRUPCOES
,(SUM(DATA_DIF)*24)/COUNT(1) AS MEDIA_HORAS_INTERROMPIDAS
FROM
(
SELECT 
SIGLA_AGENTE
,ANO
,CODIGO_UC
,DSC_ALIMENTADOR_SUBESTACAO
,DSC_SUBESTACAO_DISTRIBUICAO
,ORDEM_INTERRUPCAO
,DSC_TIPO_INTERRUPCAO
,MOTIVO_EXPURGO
,TO_TIMESTAMP(DATA_INICIO_INTERRUPCAO, 'YYYY-MM-DD HH24:MI:SS') AS DATA_INICIO
,TO_TIMESTAMP(DATA_FIM_INTERRUPCAO, 'YYYY-MM-DD HH24:MI:SS') AS DATA_FIM
,TO_DATE(DATA_FIM_INTERRUPCAO, 'YYYY-MM-DD HH24:MI:SS') - TO_DATE(DATA_INICIO_INTERRUPCAO, 'YYYY-MM-DD HH24:MI:SS') AS DATA_DIF
,FATO_GERADOR_INTERRUPCAO
,NUM_NIVEL_TENSAO
,NUM_UNIDADE_CONSUMIDORA
,NUM_CONSUMIDOR_CONJUNTO
FROM INTERRUPCOES_ANEEL_2022
WHERE TO_DATE(DATA_FIM_INTERRUPCAO, 'YYYY-MM-DD HH24:MI:SS') - TO_DATE(DATA_INICIO_INTERRUPCAO, 'YYYY-MM-DD HH24:MI:SS') >= 0.0020833333333
AND MOTIVO_EXPURGO = '0'
--AND (SIGLA_AGENTE = 'CPFL-PAULISTA' OR SIGLA_AGENTE = 'CPFL- PIRATININGA' OR SIGLA_AGENTE = 'CPFL Jaguari' OR SIGLA_AGENTE = 'RGE SUL')
AND NUM_UNIDADE_CONSUMIDORA > 0
)
GROUP BY SIGLA_AGENTE;






